### ISSUE TITLE
False positives in GitLab using the Code Climate output

### ISSUE THREAD

**Issue by terje2001** [tomasbjerre/violations-maven-plugin#1]
First off: Fantastic plugin, really appreciate your work and it helps us a lot!

Problem: We use your tool create a code climate output that we then import into GitLab. When code is changed, we get a lot of false positives changes, where the same change will be listed (by Gitlab) as both new and fixed, causing us to miss the 'real' issue.

I think the problem is that 
 - the hash generation used for 'fingerprint' field in the code climate output by violations-maven-plugin seems to includes the line number, and,
 - gitlab uses the fingerprint exclusively to identify new and fixed items (see https://gitlab.com/gitlab-org/gitlab/-/blob/9b319658ece205d3960414ab9d7887a2f1c1cf24/ee/app/assets/javascripts/vue_merge_request_widget/workers/code_quality_comparison_worker.js)

Therefore, would it be possible to create a unique hash as fingerprint per item that does not include line number as input?

**Comment by tomasbjerre** [comment]
Released in 1.36. Open issue again if not working!
