### ISSUE TITLE
file path is wrong in GitLab MR widget

### ISSUE THREAD

**Issue by shaunthegeek** [tomasbjerre/violations-maven-plugin#3]
### Summary

the file path in GitLab MR widget is wrong, so the URL is 404

### Steps to reproduce

1. use `violations-maven-plugin` for checkstyle in Java project
2. run `./mvnw validate` in GitLab CI

### Example Project

https://jihulab.com/ultimate-plan/demo/java-17-maven-demo/-/merge_requests/1

### What is the current *bug* behavior?

file path: `/builds/ultimate-plan/demo/java-17-maven-demo/src/main/java/org/owasp/webgoat/lessons/jwt/JWTFinalEndpoint.java:96`

url: https://jihulab.com/ultimate-plan/demo/java-17-maven-demo/-/blob/9e6c41a0591484eeaab818dd25fc194c594af37b//builds/ultimate-plan/demo/java-17-maven-demo/src/main/java/org/owasp/webgoat/lessons/jwt/JWTFinalEndpoint.java#L96

### What is the expected *correct* behavior?

file path: `src/main/java/org/owasp/webgoat/lessons/jwt/JWTFinalEndpoint.java:96`

url: https://jihulab.com/ultimate-plan/demo/java-17-maven-demo/-/blob/9e6c41a0591484eeaab818dd25fc194c594af37b/src/main/java/org/owasp/webgoat/lessons/jwt/JWTFinalEndpoint.java#L96

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/4971414/191152073-d296232a-6639-4da8-beca-355a406aca3a.png)

![image](https://user-images.githubusercontent.com/4971414/191152112-a441d52a-2539-4abe-af08-62ba8478b748.png)

`target/checkstyle-result.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="9.3">
<file name="/Volumes/Code/ultimate-plan/demo/WebGoat/src/main/java/org/dummy/insecure/framework/VulnerableTaskHolder.java">
<error line="5" column="1" severity="warning" message="foo" source="com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck"/>
```

`target/pmd.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd" version="6.49.0" timestamp="2022-09-20T10:08:44.599">
<file name="/Volumes/Code/ultimate-plan/demo/WebGoat/src/main/java/org/owasp/webgoat/container/WebSecurityConfig.java">
<violation beginline="34" endline="34" begincolumn="1" endcolumn="49" rule="UnnecessaryImport" ruleset="Code Style" package="org.owasp.webgoat.container" class="WebSecurityConfig" externalInfoUrl="https://pmd.github.io/pmd-6.49.0/pmd_rules_java_codestyle.html#unnecessaryimport" priority="4">
Unused import 'org.owasp.webgoat.container.i18n.Language'
</violation>
```

`gl-code-quality-report.json`

```json
[
  {
    "description": "tab in line",
    "fingerprint": "871ea4ab645d5d0e497b475c186acb5a57f764419e9ba4cd3dae8aa0a1093e10",
    "location": {
      "path": "/Volumes/Code/ultimate-plan/demo/WebGoat/src/main/java/org/dummy/insecure/framework/VulnerableTaskHolder.java",
      "lines": {
        "begin": 73
      }
    }
]
```

**Comment by tomasbjerre** [comment]
Relates to https://github.com/tomasbjerre/violations-lib/issues/123

**Comment by tomasbjerre** [comment]
Released a fix, open issue again if not working.

**Comment by shaunthegeek** [comment]
Great!
`v1.50.4` is fine. https://jihulab.com/premium-plan/scenarios/checkstyle-gitlab-mr-java-8-maven/-/merge_requests/1
