### ISSUE TITLE
how to make the build failed?

### ISSUE THREAD

**Issue by dhursan** [tomasbjerre/violations-maven-plugin#6]
Hi, 

I have read in the readme.md that it can fail the build optionally if violations are fount but haven't found any config option to do so. How can I do that?

**Comment by tomasbjerre** [comment]
Will fail the build if total number of found violations is higher 
`<maxViolations>99999999</maxViolations>`

**Comment by dhursan** [comment]
Thank you!

**Comment by dhursan** [comment]
Thank you!
